/*
 * DBSettingPanel.java
 *
 * Created on 2007年11月5日, 下午9:35
 */
package com.nci.ums.desktop.panels;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.nci.ums.desktop.ConsoleUtil;

/**
 * 
 * @author Qil.Wong
 */
public class DBSettingPanel extends javax.swing.JPanel implements Setting {

	private static String propFile1 = "/resources/umsdb.props";
	private static String propFile2 = "/com/nci/ums/desktop/umsdb.props";

	/** Creates new form DBSettingPanel */
	public DBSettingPanel() {
		initComponents();
	}

	public void implSetting() throws IOException {

		String path1 = getClass().getResource(propFile1).getPath();
		String path2 = getClass().getResource(propFile2).getPath();
		ConsoleUtil.replacePropFile(new String[] { "drivers", "url", "pool_name",
				"user", "password", "maxActive", "maxIdle", "maxWait" },
				new String[] { driversField.getText(), urlField.getText(),
						poolNameField.getText(), userField.getText(),
						new String(passwordField.getPassword()),
						maxActiveCombo.getSelectedItem().toString(),
						maxIdleCombo.getSelectedItem().toString(),
						maxWaitCombo.getSelectedItem().toString() }, path1);
		ConsoleUtil.replacePropFile(new String[] { "drivers", "url", "pool_name",
				"user", "password", "maxActive", "maxIdle", "maxWait" },
				new String[] { driversField.getText(), urlField.getText(),
						poolNameField.getText(), userField.getText(),
						new String(passwordField.getPassword()),
						maxActiveCombo.getSelectedItem().toString(),
						maxIdleCombo.getSelectedItem().toString(),
						maxWaitCombo.getSelectedItem().toString() }, path2);
	}

	public void initSetting() throws IOException {
		Properties dbProps_ = new Properties();
		InputStream is = getClass().getResourceAsStream(propFile1);
		dbProps_.load(is);
		this.driversField.setText(dbProps_.getProperty("drivers"));
		this.urlField.setText(dbProps_.getProperty("url"));
		this.poolNameField.setText(dbProps_.getProperty("pool_name"));
		this.userField.setText(dbProps_.getProperty("user"));
		this.passwordField.setText(dbProps_.getProperty("password"));
		this.maxActiveCombo.setSelectedItem(dbProps_.getProperty("maxActive"));
		this.maxIdleCombo.setSelectedItem(dbProps_.getProperty("maxIdle"));
		this.maxWaitCombo.setSelectedItem(dbProps_.getProperty("maxWait"));
		is.close();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driversLabel = new javax.swing.JLabel();
        driversField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        poolNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maxIdleCombo = new javax.swing.JComboBox();
        maxActiveCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        maxWaitCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        driversLabel.setText(ConsoleUtil.getLocaleString("Drivers:")); // NOI18N

        driversField.setToolTipText(ConsoleUtil.getLocaleString("Dirver_Tooltip")); // NOI18N

        jLabel1.setText(ConsoleUtil.getLocaleString("URL:")); // NOI18N

        urlField.setToolTipText(ConsoleUtil.getLocaleString("URL_Tooltip")); // NOI18N

        jLabel2.setText(ConsoleUtil.getLocaleString("Pool:")); // NOI18N

        jLabel3.setText(ConsoleUtil.getLocaleString("User:")); // NOI18N

        jLabel4.setText(ConsoleUtil.getLocaleString("Password:")); // NOI18N

        jLabel5.setText(ConsoleUtil.getLocaleString("MaxActive:")); // NOI18N

        jLabel6.setText(ConsoleUtil.getLocaleString("MaxIdle:")); // NOI18N

        maxIdleCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "50", "100", "150", "200", "300", "400" }));

        maxActiveCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "50", "100", "150", "200", "300", "400" }));

        jLabel7.setText(ConsoleUtil.getLocaleString("MaxWait:")); // NOI18N

        maxWaitCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3000", "5000", "10000", "15000", "25000", "50000" }));

        jLabel8.setText("ms");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel5))
                        .add(7, 7, 7)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(maxIdleCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(maxActiveCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(31, 31, 31)
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(maxWaitCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8))))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(driversLabel)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3))))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(userField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(poolNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(urlField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(driversField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(passwordField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {maxActiveCombo, maxIdleCombo, maxWaitCombo}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(driversLabel)
                    .add(driversField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(urlField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(poolNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(userField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(passwordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel5)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel8)
                        .add(maxActiveCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(maxWaitCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel7)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(maxIdleCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {driversField, passwordField, poolNameField, urlField, userField}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField driversField;
    private javax.swing.JLabel driversLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox maxActiveCombo;
    private javax.swing.JComboBox maxIdleCombo;
    private javax.swing.JComboBox maxWaitCombo;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField poolNameField;
    private javax.swing.JTextField urlField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
