/*
 * EmailSettingPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nci.ums.desktop.panels;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import javax.swing.JTextField;

import com.nci.ums.desktop.ConsoleUtil;
import com.nci.ums.desktop.bean.NumOnlyDocument;

/**
 * 
 * @author __USER__
 */
public class EmailSettingPanel extends javax.swing.JPanel implements Setting {

	private String propFile = "/resources/email.props";

	/** Creates new form EmailSettingPanel */
	public EmailSettingPanel() {
		initComponents();
		setNumOnlyDocs();
	}

	private void setNumOnlyDocs() {
		smtpIPText1.setDocument(new NumOnlyDocument(3));
		smtpIPText2.setDocument(new NumOnlyDocument(3));
		smtpIPText3.setDocument(new NumOnlyDocument(3));
		smtpIPText4.setDocument(new NumOnlyDocument(3));
		pop3IPText1.setDocument(new NumOnlyDocument(3));
		pop3IPText2.setDocument(new NumOnlyDocument(3));
		pop3IPText3.setDocument(new NumOnlyDocument(3));
		pop3IPText4.setDocument(new NumOnlyDocument(3));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ipText4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ipText2 = new javax.swing.JTextField();
        ipText3 = new javax.swing.JTextField();
        ipText1 = new javax.swing.JTextField();
        ipText8 = new javax.swing.JTextField();
        ipText6 = new javax.swing.JTextField();
        ipText7 = new javax.swing.JTextField();
        ipText5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        smtpIPText1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        smtpIPText2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        smtpIPText3 = new javax.swing.JTextField();
        smtpIPText4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pop3IPText1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        pop3IPText2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pop3IPText3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pop3IPText4 = new javax.swing.JTextField();
        umsEmailText = new javax.swing.JTextField();
        umsEmailPswText = new javax.swing.JPasswordField();
        domainText = new javax.swing.JTextField();
        umsAdminEmailText = new javax.swing.JTextField();

        jLabel10.setText(".");

        jLabel8.setText(".");

        jLabel9.setText(".");

        jLabel14.setText(".");

        jLabel15.setText(".");

        jLabel16.setText(".");

        jLabel1.setText(ConsoleUtil.getLocaleString("SMTP_Server_IP:")); // NOI18N

        jLabel2.setText(ConsoleUtil.getLocaleString("Pop3__Server_IP:")); // NOI18N

        jLabel3.setText(ConsoleUtil.getLocaleString("UMS_Email:")); // NOI18N

        jLabel4.setText(ConsoleUtil.getLocaleString("UMS_Email_Password:")); // NOI18N

        jLabel5.setText(ConsoleUtil.getLocaleString("Domain:")); // NOI18N

        jLabel6.setText(ConsoleUtil.getLocaleString("UMS_Administrator_Email:")); // NOI18N

        jLabel11.setText(".");

        jLabel12.setText(".");

        jLabel13.setText(".");

        jLabel7.setText(ConsoleUtil.getLocaleString("EmailPanel_Info")); // NOI18N

        jLabel17.setText(".");

        jLabel18.setText(".");

        jLabel19.setText(".");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel3)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(umsAdminEmailText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(domainText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(umsEmailPswText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(umsEmailText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                        .add(pop3IPText1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel17))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                        .add(smtpIPText1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel11)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(layout.createSequentialGroup()
                                        .add(pop3IPText2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel18)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(pop3IPText3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel19)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(pop3IPText4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(smtpIPText2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel12)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(smtpIPText3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel13)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(smtpIPText4)))))
                        .addContainerGap())))
        );

        layout.linkSize(new java.awt.Component[] {pop3IPText1, pop3IPText2, pop3IPText3, pop3IPText4, smtpIPText1, smtpIPText2, smtpIPText3}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(smtpIPText1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11)
                    .add(smtpIPText2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(smtpIPText3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(jLabel1)
                    .add(smtpIPText4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pop3IPText1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17)
                    .add(pop3IPText2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18)
                    .add(pop3IPText3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel19)
                    .add(pop3IPText4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(umsEmailText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(umsEmailPswText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(domainText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(umsAdminEmailText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {domainText, pop3IPText1, pop3IPText2, pop3IPText3, pop3IPText4, smtpIPText1, smtpIPText2, smtpIPText3, smtpIPText4, umsAdminEmailText, umsEmailPswText, umsEmailText}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField domainText;
    private javax.swing.JTextField ipText1;
    private javax.swing.JTextField ipText2;
    private javax.swing.JTextField ipText3;
    private javax.swing.JTextField ipText4;
    private javax.swing.JTextField ipText5;
    private javax.swing.JTextField ipText6;
    private javax.swing.JTextField ipText7;
    private javax.swing.JTextField ipText8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pop3IPText1;
    private javax.swing.JTextField pop3IPText2;
    private javax.swing.JTextField pop3IPText3;
    private javax.swing.JTextField pop3IPText4;
    private javax.swing.JTextField smtpIPText1;
    private javax.swing.JTextField smtpIPText2;
    private javax.swing.JTextField smtpIPText3;
    private javax.swing.JTextField smtpIPText4;
    private javax.swing.JTextField umsAdminEmailText;
    private javax.swing.JPasswordField umsEmailPswText;
    private javax.swing.JTextField umsEmailText;
    // End of variables declaration//GEN-END:variables

	public void implSetting() throws IOException {
		String[] parameterNames = new String[] { "host", "pop3", "loginName",
				"loginPwd", "domain", "UMSAdminEmail" };
		StringBuffer hostIP = new StringBuffer();
		hostIP.append(smtpIPText1.getText()).append(".").append(
				smtpIPText2.getText()).append(".")
				.append(smtpIPText3.getText()).append(".").append(
						smtpIPText4.getText());
		StringBuffer pop3IP = new StringBuffer();
		pop3IP.append(pop3IPText1.getText()).append(".").append(
				pop3IPText2.getText()).append(".")
				.append(pop3IPText3.getText()).append(".").append(
						pop3IPText4.getText());
		String[] parameterValues = new String[] { hostIP.toString(),
				pop3IP.toString(), umsEmailText.getText().trim(),
				new String(umsEmailPswText.getPassword()),
				domainText.getText(), umsAdminEmailText.getText() };
		String path = getClass().getResource(propFile).getPath();
		ConsoleUtil.replacePropFile(parameterNames, parameterValues, path);
	}

	public void initSetting() throws IOException {
		Properties props = new Properties();
		InputStream is = getClass().getResourceAsStream(propFile);
		props.load(is);
		String hostIP = props.getProperty("host");
		ConsoleUtil.setIPTo4TextField(hostIP, new JTextField[]{smtpIPText1,smtpIPText2,smtpIPText3,smtpIPText4});
		String pop3IP = props.getProperty("pop3");
		ConsoleUtil.setIPTo4TextField(pop3IP,  new JTextField[]{pop3IPText1,pop3IPText2,pop3IPText3,pop3IPText4});
		String umsEmail = props.getProperty("loginName");
		this.umsEmailText.setText(umsEmail);
		String umsEmailPsw = props.getProperty("loginPwd");
		this.umsEmailPswText.setText(umsEmailPsw);
		String domain = props.getProperty("domain");
		this.domainText.setText(domain);
		String umsAdminEmail = props.getProperty("UMSAdminEmail");
		this.umsAdminEmailText.setText(umsAdminEmail);
		is.close();
	}

}