/*
 * MobileSettingPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nci.ums.desktop.panels;

import java.io.IOException;
import java.io.InputStream;
import java.util.Iterator;
import java.util.Properties;

import javax.swing.DefaultListModel;

import com.nci.ums.desktop.ConsoleUtil;
import com.nci.ums.desktop.bean.NumOnlyDocument;

/**
 *
 * @author  __USER__
 */
public class MobileSettingPanel extends javax.swing.JPanel implements Setting {

	private String propFile = "/resources/Mobileserver.properties";
	private static String cm = "chinamobile";
	private static String cu = "chinaunicom";

	/** Creates new form MobileSettingPanel */
	public MobileSettingPanel() {
		initComponents();
		cmAddText.setDocument(new NumOnlyDocument(3));
		cuAddText.setDocument(new NumOnlyDocument(3));
		cmSPText.setDocument(new NumOnlyDocument(21));
		cuSPText.setDocument(new NumOnlyDocument(21));
		cmMaxText.setDocument(new NumOnlyDocument(3));
		cuMaxText.setDocument(new NumOnlyDocument(3));
                enterpriseCode_CMText.setDocument(new NumOnlyDocument(10));
                enterpriseCode_CUText.setDocument(new NumOnlyDocument(10));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cmNumList = new javax.swing.JList();
        cmAddText = new javax.swing.JTextField();
        cmAddBtn = new javax.swing.JButton();
        cmRemoveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cuNumList = new javax.swing.JList();
        cuAddText = new javax.swing.JTextField();
        cuAddBtn = new javax.swing.JButton();
        cuRemoveBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmSPText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmMaxText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cuSPText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cuMaxText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        enterpriseCode_CMText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        enterpriseCode_CUText = new javax.swing.JTextField();

        cmNumList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(cmNumList);

        cmAddBtn.setText(ConsoleUtil.getLocaleString("AddNO")); // NOI18N
        cmAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmAddBtnActionPerformed(evt);
            }
        });

        cmRemoveBtn.setText(ConsoleUtil.getLocaleString("RemoveNO")); // NOI18N
        cmRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmRemoveBtnActionPerformed(evt);
            }
        });

        jLabel1.setText(ConsoleUtil.getLocaleString("China_Mobile_Phone_Numbers:")); // NOI18N

        jLabel2.setText(ConsoleUtil.getLocaleString("China_Unicom_Phone_Numbers:")); // NOI18N

        jScrollPane2.setViewportView(cuNumList);

        cuAddBtn.setText(ConsoleUtil.getLocaleString("AddNO")); // NOI18N
        cuAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuAddBtnActionPerformed(evt);
            }
        });

        cuRemoveBtn.setText(ConsoleUtil.getLocaleString("RemoveNO")); // NOI18N
        cuRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuRemoveBtnActionPerformed(evt);
            }
        });

        jLabel3.setText(ConsoleUtil.getLocaleString("China_Mobile__SP_No.:")); // NOI18N

        jLabel4.setText(ConsoleUtil.getLocaleString("China_Mobile__SP_Max_Length:")); // NOI18N

        jLabel5.setText(ConsoleUtil.getLocaleString("China_Unicom_SP_No.")); // NOI18N

        jLabel6.setText(ConsoleUtil.getLocaleString("New:")); // NOI18N

        jLabel7.setText(ConsoleUtil.getLocaleString("New:")); // NOI18N

        jLabel8.setText(ConsoleUtil.getLocaleString("China_Unicom_SP_Max_Length:")); // NOI18N

        jLabel9.setText(ConsoleUtil.getLocaleString("China_Mobile_EnterpriseCode")); // NOI18N

        jLabel10.setText(ConsoleUtil.getLocaleString("China_Unicom_EnterpriseCode"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cmAddBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cmRemoveBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cmSPText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cuSPText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmAddText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .add(enterpriseCode_CMText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 26, 26)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cuAddBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cuAddText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cuRemoveBtn)))
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(enterpriseCode_CUText)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cuMaxText)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cmMaxText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {cuAddBtn, cuRemoveBtn}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {cmAddBtn, cmRemoveBtn}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {jScrollPane1, jScrollPane2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(cuAddText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cuAddBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cuRemoveBtn))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane2, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(cmAddText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel6))
                                .add(8, 8, 8)
                                .add(cmAddBtn)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cmRemoveBtn)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3)
                    .add(cmSPText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel4)
                        .add(cmMaxText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(cuSPText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(cuMaxText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(enterpriseCode_CMText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(jLabel10)
                    .add(enterpriseCode_CUText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(23, 23, 23))
        );

        layout.linkSize(new java.awt.Component[] {jScrollPane1, jScrollPane2}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

	
	private void cuRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {		
		if(cuNumList.getSelectedIndex()>=0){
			DefaultListModel cuListModel = (DefaultListModel)cuNumList.getModel();
			cuListModel.remove(cuNumList.getSelectedIndex());
		}
	}

	
	private void cuAddBtnActionPerformed(java.awt.event.ActionEvent evt) {
		String newNum = cuAddText.getText();
		if(!newNum.equals("")){
			DefaultListModel cuListModel = (DefaultListModel)cuNumList.getModel();
			cuListModel.addElement(newNum);
		}
	}

	
	private void cmRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {		
		if(cmNumList.getSelectedIndex()>=0){
			DefaultListModel cmListModel = (DefaultListModel)cmNumList.getModel();
			cmListModel.remove(cmNumList.getSelectedIndex());
		}
	}

	
	private void cmAddBtnActionPerformed(java.awt.event.ActionEvent evt) {
		String newNum = cmAddText.getText();
		if(!newNum.equals("")){
			DefaultListModel cmListModel = (DefaultListModel)cmNumList.getModel();
			cmListModel.addElement(newNum);
		}
	}

	public void implSetting() throws IOException {
		DefaultListModel cmListModel = (DefaultListModel)cmNumList.getModel();
		DefaultListModel cuListModel = (DefaultListModel)cuNumList.getModel();		
		String[] parameterNames = new String[cmListModel.size()+cuListModel.size()+6];
		String[] parameterValues = new String[cmListModel.size()+cuListModel.size()+6];
		for(int i=0;i<cmListModel.size();i++){
			parameterNames[i]=(String)cmListModel.getElementAt(i);
			parameterValues[i]="chinamobile";
		}
		for(int i=0;i<cuListModel.size();i++){
			parameterNames[cmListModel.size()+i]=(String)cuListModel.getElementAt(i);
			parameterValues[cmListModel.size()+i]="chinaunicom";
		}
		parameterNames[cmListModel.size()+cuListModel.size()]="UMSCenter_cm";
		parameterValues[cmListModel.size()+cuListModel.size()]=cmSPText.getText();
		parameterNames[cmListModel.size()+cuListModel.size()+1]="UMSCenter_cu";
		parameterValues[cmListModel.size()+cuListModel.size()+1]=cuSPText.getText();
		parameterNames[cmListModel.size()+cuListModel.size()+2]="SP_ext_max_cm";
		parameterValues[cmListModel.size()+cuListModel.size()+2]=cmMaxText.getText();
		parameterNames[cmListModel.size()+cuListModel.size()+3]="SP_ext_max_cu";
		parameterValues[cmListModel.size()+cuListModel.size()+3]=cuMaxText.getText();
                parameterNames[cmListModel.size()+cuListModel.size()+4]="EnterpriseCode_CM";
		parameterValues[cmListModel.size()+cuListModel.size()+4]=enterpriseCode_CMText.getText();
                parameterNames[cmListModel.size()+cuListModel.size()+5]="EnterpriseCode_CU";
		parameterValues[cmListModel.size()+cuListModel.size()+5]=enterpriseCode_CUText.getText();
		String path = getClass().getResource(propFile).getPath();
		ConsoleUtil.replacePropFile(parameterNames, parameterValues, path);
	}

	public void initSetting() throws IOException {
		DefaultListModel cmListModel = new DefaultListModel();
		DefaultListModel cuListModel = new DefaultListModel();
		Properties props = new Properties();
		InputStream is = getClass().getResourceAsStream(propFile);
		props.load(is);
		Iterator it = props.keySet().iterator();
		while (it.hasNext()) {
			String key = it.next().toString();
			if (key.equals("UMSCenter_cm")) {//中国移动sp号
				cmSPText.setText(props.getProperty(key));
			} else if (key.equals("UMSCenter_cu")) {//中国联通sp号
				cuSPText.setText(props.getProperty(key));
			} else if (key.equals("SP_ext_max_cm")) {//中国移动sp号最大扩展位数
				cmMaxText.setText(props.getProperty(key));
			} else if (key.equals("SP_ext_max_cu")) {//中国联通sp号最大扩展位数
				cuMaxText.setText(props.getProperty(key));
			}else if(key.equals("EnterpriseCode_CM")){
                            enterpriseCode_CMText.setText(props.getProperty(key));
                        }  else if(key.equals("EnterpriseCode_CU")){
                            enterpriseCode_CUText.setText(props.getProperty(key));
                        }                       
                        else {//移动联通号段分类
				if (props.getProperty(key).equals(cm))
					cmListModel.addElement(key);
				else
					cuListModel.addElement(key);
			}
		}
		cmNumList.setModel(cmListModel);
		cuNumList.setModel(cuListModel);
		is.close();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmAddBtn;
    private javax.swing.JTextField cmAddText;
    private javax.swing.JTextField cmMaxText;
    private javax.swing.JList cmNumList;
    private javax.swing.JButton cmRemoveBtn;
    private javax.swing.JTextField cmSPText;
    private javax.swing.JButton cuAddBtn;
    private javax.swing.JTextField cuAddText;
    private javax.swing.JTextField cuMaxText;
    private javax.swing.JList cuNumList;
    private javax.swing.JButton cuRemoveBtn;
    private javax.swing.JTextField cuSPText;
    private javax.swing.JTextField enterpriseCode_CMText;
    private javax.swing.JTextField enterpriseCode_CUText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}