/*
 * DBSettingPanel.java
 *
 * Created on 2007��11��5��, ����9:35
 */
package com.ums.demo.panels;

import com.ums.demo.interfaces.Setting;
import com.ums.demo.util.UMSDemoUtil;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Qil.Wong
 */
public class DBSettingPanel extends javax.swing.JPanel implements Setting {

    /** Creates new form DBSettingPanel */
    public DBSettingPanel() {
        initComponents();
        initSetting();
    }

    public void implSetting() {
        try {
            UMSDemoUtil.replace(new String[]{"drivers","url","pool_name","user","password","maxActive","maxIdle","maxWait"}, 
                    new String[]{driversField.getText(),urlField.getText(),poolNameField.getText(),
                    userField.getText(),new String(passwordField.getPassword()),maxActiveCombo.getSelectedItem().toString(),
                    maxIdleCombo.getSelectedItem().toString(),maxWaitCombo.getSelectedItem().toString()},
                    System.getProperty("user.dir")+"/conf/umsdb.props");
        } catch (IOException ex) {
            Logger.getLogger(DBSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }

    public void initSetting() {
        Properties dbProps_ = new Properties();
        try {
            InputStream is = new FileInputStream(System.getProperty("user.dir")+"/conf/umsdb.props");
            dbProps_.load(is);
            this.driversField.setText(dbProps_.getProperty("drivers"));
            this.urlField.setText(dbProps_.getProperty("url"));
            this.poolNameField.setText(dbProps_.getProperty("pool_name"));
            this.userField.setText(dbProps_.getProperty("user"));
            this.passwordField.setText(dbProps_.getProperty("password"));  
            this.maxActiveCombo.setSelectedItem(dbProps_.getProperty("maxActive"));
            this.maxIdleCombo.setSelectedItem(dbProps_.getProperty("maxIdle"));
            this.maxWaitCombo.setSelectedItem(dbProps_.getProperty("maxWait"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driversLabel = new javax.swing.JLabel();
        driversField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        poolNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maxIdleCombo = new javax.swing.JComboBox();
        maxActiveCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        maxWaitCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        driversLabel.setText("Drivers:");

        jLabel1.setText("URL:");

        jLabel2.setText("Pool_Name:");

        jLabel3.setText("User:");

        jLabel4.setText("Password:");

        jLabel5.setText("MaxActive:");

        jLabel6.setText("MaxIdle:");

        maxIdleCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5", "8", "10" }));

        maxActiveCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "10", "20", "50" }));

        jLabel7.setText("MaxWait:");

        maxWaitCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3000", "5000", "10000", "15000" }));

        jLabel8.setText("ms");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel5))
                        .add(7, 7, 7)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(maxIdleCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(maxActiveCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(31, 31, 31)
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(maxWaitCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8))))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(driversLabel)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3))))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(userField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(poolNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(urlField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(driversField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(passwordField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {maxActiveCombo, maxIdleCombo, maxWaitCombo}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(driversLabel)
                    .add(driversField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(urlField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(poolNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(userField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(passwordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel5)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel8)
                        .add(maxActiveCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(maxWaitCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel7)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(maxIdleCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {driversField, passwordField, poolNameField, urlField, userField}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField driversField;
    private javax.swing.JLabel driversLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox maxActiveCombo;
    private javax.swing.JComboBox maxIdleCombo;
    private javax.swing.JComboBox maxWaitCombo;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField poolNameField;
    private javax.swing.JTextField urlField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
