/*
 * WSDLSettingPanel.java
 *
 * Created on 2007��11��5��, ����8:26
 */

package com.ums.demo.panels;

import com.ums.demo.interfaces.Setting;
import com.ums.demo.util.UMSDemoUtil;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Qil.Wong
 */
public class WSDLSettingPanel extends javax.swing.JPanel implements Setting{
    
    /** Creates new form WSDLSettingPanel */
    public WSDLSettingPanel() {
        initComponents();
        initSetting();
    }
    
    
    public void implSetting(){
        try {
            String wsdlLocation = this.getWsdlField().getText().trim();
            UMSDemoUtil.replace(new String[]{"wsdl_msg_send"}, new String[]{wsdlLocation}, System.getProperty("user.dir")+"/conf/wsdl.props");
        } catch (IOException ex) {
            Logger.getLogger(WSDLSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void initSetting(){
        InputStream is = null;
        try {
            Properties prop = new Properties();
            is = new FileInputStream(new File(System.getProperty("user.dir")+"/conf/wsdl.props"));
            prop.load(is);
            this.getWsdlField().setText(prop.getProperty("wsdl_msg_send"));
        } catch (IOException ex) {
            Logger.getLogger(WSDLSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                is.close();
            } catch (IOException ex) {
                Logger.getLogger(WSDLSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        wsdlField = new javax.swing.JTextField();

        jLabel1.setText("WSDL Location:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(wsdlField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(wsdlField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField wsdlField;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getWsdlField() {
        return wsdlField;
    }

    public void setWsdlField(javax.swing.JTextField wsdlField) {
        this.wsdlField = wsdlField;
    }
    
}
