/*
 * ScrollablePopupDemo.java
 *
 * Created on June 12, 2007, 11:16 PM
 */

package dyno.swing.beans.test;

import dyno.swing.beans.ScrollablePopupFactory;
import java.awt.EventQueue;
import javax.swing.PopupFactory;
import javax.swing.UIManager;

/**
 *
 * @author  rehte
 */
public class ScrollablePopupDemo extends javax.swing.JFrame {
    
    /** Creates new form ScrollablePopupDemo */
    public ScrollablePopupDemo() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" 生成的代码 ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem8 = new javax.swing.JRadioButtonMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem9 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem10 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem9 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("Hold your mouse here to popup a tooltip!");
        jLabel1.setToolTipText("ToolTip, Popup a tooltip!");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("<html>Please resize the window so that<p> some popup can extend beyond the top window</html>");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Horizontally scrollable popup");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Vertically scrollable popup");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);
        jMenu7.setText("Menu");
        jMenuItem22.setText("Item");
        jMenu7.add(jMenuItem22);

        jMenuItem23.setText("Item");
        jMenu7.add(jMenuItem23);

        jCheckBoxMenuItem7.setText("CheckBox");
        jMenu7.add(jCheckBoxMenuItem7);

        jRadioButtonMenuItem8.setText("RadioButton");
        jMenu7.add(jRadioButtonMenuItem8);

        jMenu8.setText("Menu");
        jMenuItem26.setText("Item");
        jMenu8.add(jMenuItem26);

        jMenuItem27.setText("Item");
        jMenu8.add(jMenuItem27);

        jRadioButtonMenuItem9.setText("RadioButton");
        jMenu8.add(jRadioButtonMenuItem9);

        jCheckBoxMenuItem8.setText("CheckBox");
        jMenu8.add(jCheckBoxMenuItem8);

        jMenu9.setText("Menu");
        jMenuItem28.setText("Item");
        jMenu9.add(jMenuItem28);

        jMenuItem29.setText("Item");
        jMenu9.add(jMenuItem29);

        jRadioButtonMenuItem10.setText("RadioButton");
        jMenu9.add(jRadioButtonMenuItem10);

        jCheckBoxMenuItem9.setText("CheckBox");
        jMenu9.add(jCheckBoxMenuItem9);

        jMenuItem30.setText("Item");
        jMenu9.add(jMenuItem30);

        jMenu8.add(jMenu9);

        jMenuItem31.setText("Item");
        jMenu8.add(jMenuItem31);

        jMenu7.add(jMenu8);

        jMenuItem24.setText("Item");
        jMenu7.add(jMenuItem24);

        jMenu7.add(jSeparator6);

        jMenuItem25.setText("Item");
        jMenu7.add(jMenuItem25);

        jMenuBar2.add(jMenu7);

        jInternalFrame1.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
        jInternalFrame1.setBounds(60, 50, 240, 150);
        jDesktopPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Menu");
        jMenuItem1.setText("Item");
        jMenu1.add(jMenuItem1);

        jCheckBoxMenuItem1.setText("CheckBox");
        jMenu1.add(jCheckBoxMenuItem1);

        jMenu1.add(jSeparator1);

        jMenu4.setText("Menu");
        jMenuItem2.setText("Item");
        jMenu4.add(jMenuItem2);

        jCheckBoxMenuItem2.setText("CheckBox");
        jMenu4.add(jCheckBoxMenuItem2);

        jRadioButtonMenuItem1.setText("RadioButton");
        jMenu4.add(jRadioButtonMenuItem1);

        jMenu5.setText("Menu");
        jMenuItem3.setText("Item");
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Item");
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Item");
        jMenu5.add(jMenuItem5);

        jMenu5.add(jSeparator2);

        jMenuItem6.setText("Item");
        jMenu5.add(jMenuItem6);

        jRadioButtonMenuItem7.setText("RadioButton");
        jMenu5.add(jRadioButtonMenuItem7);

        jMenu4.add(jMenu5);

        jMenuItem7.setText("Item");
        jMenu4.add(jMenuItem7);

        jRadioButtonMenuItem2.setText("RadioButton");
        jMenu4.add(jRadioButtonMenuItem2);

        jMenuItem8.setText("Item");
        jMenu4.add(jMenuItem8);

        jRadioButtonMenuItem3.setText("RadioButton");
        jMenu4.add(jRadioButtonMenuItem3);

        jMenu1.add(jMenu4);

        jMenuItem9.setText("Item");
        jMenu1.add(jMenuItem9);

        jMenu1.add(jSeparator3);

        jMenuItem10.setText("Item");
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");
        jMenuItem11.setText("Item");
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Item");
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Item");
        jMenu2.add(jMenuItem13);

        jMenu6.setText("Menu");
        jMenuItem14.setText("Item");
        jMenu6.add(jMenuItem14);

        jMenuItem15.setText("Item");
        jMenu6.add(jMenuItem15);

        jMenuItem16.setText("Item");
        jMenu6.add(jMenuItem16);

        jRadioButtonMenuItem6.setText("RadioButton");
        jMenu6.add(jRadioButtonMenuItem6);

        jCheckBoxMenuItem6.setText("CheckBox");
        jMenu6.add(jCheckBoxMenuItem6);

        jMenu6.add(jSeparator5);

        jMenuItem21.setText("Item");
        jMenu6.add(jMenuItem21);

        jMenu2.add(jMenu6);

        jMenuItem17.setText("Item");
        jMenu2.add(jMenuItem17);

        jRadioButtonMenuItem5.setText("RadioButton");
        jMenu2.add(jRadioButtonMenuItem5);

        jCheckBoxMenuItem4.setText("CheckBox");
        jMenu2.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem5.setText("CheckBox");
        jMenu2.add(jCheckBoxMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menu");
        jMenuItem18.setText("Item");
        jMenu3.add(jMenuItem18);

        jMenuItem19.setText("Item");
        jMenu3.add(jMenuItem19);

        jMenuItem20.setText("Item");
        jMenu3.add(jMenuItem20);

        jRadioButtonMenuItem4.setText("RadioButton");
        jMenu3.add(jRadioButtonMenuItem4);

        jMenu3.add(jSeparator4);

        jCheckBoxMenuItem3.setText("CheckBox");
        jMenu3.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 478, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        setPopupFactory();
    }//GEN-LAST:event_jCheckBox2ActionPerformed
    
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        setPopupFactory();
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {}
        //设置自定义的PopupFactory，注意纵横都扩展，可以改变布尔值只横向或纵向扩展，或者没有动画
        PopupFactory.setSharedInstance(new ScrollablePopupFactory(true, true));
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrollablePopupDemo().setVisible(true);
            }
        });
    }
    
    private void setPopupFactory() {
        PopupFactory.setSharedInstance(new ScrollablePopupFactory(jCheckBox1.isSelected(), jCheckBox2.isSelected()));
    }
    
    // 变量声明 - 不进行修改//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem10;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // 变量声明结束//GEN-END:variables
    
}
