/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransmitSocketPanel.java
 *
 * Created on 2009-8-27, 21:49:51
 */

package com.nci.ums.transmit.demo;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.UnknownHostException;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import com.nci.ums.jmx.desktop.bean.SwingWorker;
import com.nci.ums.transmit.client.DataReceivedHandler;
import com.nci.ums.transmit.client.RequestHandler;
import com.nci.ums.transmit.client.TransmitClient;
import com.nci.ums.transmit.client.sender.TransmitFileSender;
import com.nci.ums.transmit.client.sender.TransmitSender;
import com.nci.ums.transmit.common.IllegalCommandException;
import com.nci.ums.transmit.common.OutOfMaxFrameSizeException;
import com.nci.ums.transmit.common.TransmitData;
import com.nci.ums.transmit.common.UMSTransmitException;
import com.nci.ums.transmit.common.UMSTransmitLogger;
import com.nci.ums.transmit.common.message.ControlCode;
import com.nci.ums.transmit.common.message.UnPackageMessage;

/**
 * 
 * @author Qil.Wong
 */
public class TransmitSocketPanel extends javax.swing.JPanel {

	private UMSTransmitLogger logger = new DemoLogger();

	/** Creates new form TransmitSocketPanel */
	public TransmitSocketPanel() {
		initComponents();
		connectionsList.setModel(new DefaultListModel());
		pathField.setEditable(false);
		connectionsList.getSelectionModel().addListSelectionListener(
				new ListSelectionListener() {

					public void valueChanged(ListSelectionEvent e) {
						listSelectionChange(e);
					}

				});
		connectionsList.getSelectionModel().setSelectionMode(
				ListSelectionModel.SINGLE_SELECTION);
		connectBtn.setEnabled(false);
		disConnectBtn.setEnabled(false);
		fileChooseBtn.setEnabled(false);
		sendBtn.setEnabled(false);

	}

	private void listSelectionChange(ListSelectionEvent e) {
		SocketConnectionBean bean = (SocketConnectionBean) connectionsList
				.getSelectedValue();
		if (bean != null) {
			bean.setConnected(bean.isConnected());
			bean.setInfoText(bean.getInfoText());
			bean.setFilePath(bean.getFilePath());
			bean.setHex(bean.isHex());
			bean.setFileTranmit(bean.isFileTranmit());
		} else {
			pathField.setText("");
			infoArea.setText("");
			hexCheckBox.setEnabled(false);
			this.simpleInputArea.setEditable(false);
			simpleInputArea.setText("");
			hexCheckBox.setSelected(false);
			fileCheckBox.setEnabled(false);
			fileCheckBox.setSelected(false);
			fileChooseBtn.setEnabled(false);
			connectBtn.setEnabled(false);
			disConnectBtn.setEnabled(false);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSplitPane1 = new javax.swing.JSplitPane();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		connectionsList = new javax.swing.JList();
		newConnBtn = new javax.swing.JButton();
		delConnBtn = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		connectBtn = new javax.swing.JButton();
		disConnectBtn = new javax.swing.JButton();
		clearBtn = new javax.swing.JButton();
		sendBtn = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		infoArea = new javax.swing.JTextArea();
		fileCheckBox = new javax.swing.JCheckBox();
		pathField = new javax.swing.JTextField();
		fileChooseBtn = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		simpleInputArea = new javax.swing.JTextArea();
		hexCheckBox = new javax.swing.JCheckBox();
		jLabel1 = new javax.swing.JLabel();
		timesField = new javax.swing.JTextField();

		jSplitPane1.setBorder(null);
		jSplitPane1.setName("jSplitPane1"); // NOI18N

		jPanel1.setName("jPanel1"); // NOI18N

		jScrollPane1.setName("jScrollPane1"); // NOI18N

		connectionsList.setName("connectionsList"); // NOI18N
		jScrollPane1.setViewportView(connectionsList);

		newConnBtn.setText("New");
		newConnBtn.setName("newConnBtn"); // NOI18N
		newConnBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newConnBtnActionPerformed(evt);
			}
		});

		delConnBtn.setText("Delete");
		delConnBtn.setName("delConnBtn"); // NOI18N
		delConnBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				delConnBtnActionPerformed(evt);
			}
		});

		jLabel2.setText("Connections:");
		jLabel2.setName("jLabel2"); // NOI18N

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jScrollPane1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																160,
																Short.MAX_VALUE)
														.add(
																jLabel2,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																160,
																Short.MAX_VALUE)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				newConnBtn,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				77,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.add(
																				delConnBtn,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				77,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));

		jPanel1Layout.linkSize(new java.awt.Component[] { delConnBtn,
				newConnBtn }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel2)
										.add(8, 8, 8)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												419, Short.MAX_VALUE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(delConnBtn).add(
																newConnBtn))
										.addContainerGap()));

		jSplitPane1.setLeftComponent(jPanel1);

		jPanel4.setName("jPanel4"); // NOI18N

		connectBtn.setText("Connect");
		connectBtn.setName("connectBtn"); // NOI18N
		connectBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				connectBtnActionPerformed(evt);
			}
		});

		disConnectBtn.setText("Disconnect");
		disConnectBtn.setName("disConnectBtn"); // NOI18N
		disConnectBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				disConnectBtnActionPerformed(evt);
			}
		});

		clearBtn.setText("Clear");
		clearBtn.setName("clearBtn"); // NOI18N
		clearBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clearBtnActionPerformed(evt);
			}
		});

		sendBtn.setText("Send");
		sendBtn.setName("sendBtn"); // NOI18N
		sendBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sendBtnActionPerformed(evt);
			}
		});

		jScrollPane2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Output"));
		jScrollPane2.setName("jScrollPane2"); // NOI18N

		infoArea.setColumns(20);
		infoArea.setEditable(false);
		infoArea.setRows(5);
		infoArea.setName("infoArea"); // NOI18N
		jScrollPane2.setViewportView(infoArea);

		fileCheckBox.setText("File Input:");
		fileCheckBox.setEnabled(false);
		fileCheckBox.setName("fileCheckBox"); // NOI18N
		fileCheckBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fileCheckBoxActionPerformed(evt);
			}
		});

		pathField.setEditable(false);
		pathField.setName("pathField"); // NOI18N

		fileChooseBtn.setText("Choose");
		fileChooseBtn.setEnabled(false);
		fileChooseBtn.setName("fileChooseBtn"); // NOI18N
		fileChooseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fileChooseBtnActionPerformed(evt);
			}
		});

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Simple Input"));
		jPanel2.setName("jPanel2"); // NOI18N

		jScrollPane3.setBorder(null);
		jScrollPane3.setName("jScrollPane3"); // NOI18N

		simpleInputArea.setColumns(20);
		simpleInputArea.setEditable(false);
		simpleInputArea.setRows(5);
		simpleInputArea.setName("simpleInputArea"); // NOI18N
		jScrollPane3.setViewportView(simpleInputArea);

		hexCheckBox.setText("Hex Format");
		hexCheckBox.setEnabled(false);
		hexCheckBox.setName("hexCheckBox"); // NOI18N
		hexCheckBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				hexCheckBoxActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jScrollPane3,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 572,
				Short.MAX_VALUE).add(
				jPanel2Layout.createSequentialGroup().add(hexCheckBox)
						.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().add(jScrollPane3,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.UNRELATED).add(
								hexCheckBox)));

		jLabel1.setText(" Times:");
		jLabel1.setName("jLabel1"); // NOI18N

		timesField.setText("1");
		timesField.setName("timesField"); // NOI18N

		org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel4Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel4Layout
																		.createSequentialGroup()
																		.add(
																				connectBtn)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				disConnectBtn)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				clearBtn)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				172,
																				Short.MAX_VALUE)
																		.add(
																				jLabel1)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				timesField,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				40,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				sendBtn))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.add(
																				fileCheckBox)
																		.add(
																				18,
																				18,
																				18)
																		.add(
																				pathField,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				414,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				fileChooseBtn))
														.add(
																jScrollPane2,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																584,
																Short.MAX_VALUE)
														.add(
																jPanel2,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));

		jPanel4Layout.linkSize(new java.awt.Component[] { connectBtn,
				disConnectBtn }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

		jPanel4Layout.linkSize(new java.awt.Component[] { clearBtn,
				fileChooseBtn, sendBtn },
				org.jdesktop.layout.GroupLayout.HORIZONTAL);

		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jScrollPane2,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												225, Short.MAX_VALUE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												jPanel4Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(fileCheckBox)
														.add(
																pathField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(fileChooseBtn))
										.add(14, 14, 14)
										.add(
												jPanel4Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																jPanel4Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.BASELINE)
																		.add(
																				disConnectBtn)
																		.add(
																				sendBtn)
																		.add(
																				clearBtn)
																		.add(
																				timesField,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(
																				jLabel1))
														.add(connectBtn))
										.addContainerGap()));

		jSplitPane1.setRightComponent(jPanel4);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jSplitPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 789,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jSplitPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 492,
				Short.MAX_VALUE));
	}

	private void newConnBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newConnBtnActionPerformed
		NewConnPanel p = new NewConnPanel();

		int res = JOptionPane.showConfirmDialog(this, p, "New Connection",
				JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
		if (res == JOptionPane.OK_OPTION) {
			String result = p.getServerField().getText();
			int clientAddress = Integer.parseInt(p.getClientAddressField()
					.getText());
			int forwardAddress = Integer.parseInt(p.getForwardAddressField()
					.getText());
			int subServerType = p.getSubServerTypeCombo().getSelectedIndex();
			if (result != null && !result.trim().equals("")
					&& clientAddress != 0) {
				String[] s = result.split(":");
				if (s.length == 2) {
					SocketConnectionBean bean = new SocketConnectionBean();
					bean.setBindPanelBean(this);
					bean.setIp(s[0]);
					bean.setPort(Integer.parseInt(s[1]));
					bean.setClientAddress(clientAddress);
					bean.setForwardAddress(forwardAddress);
					bean.setSubServerType(subServerType);
					((DefaultListModel) connectionsList.getModel())
							.addElement(bean);
				}
			}
		}

	}

	private void delConnBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_delConnBtnActionPerformed
		if (connectionsList.getSelectedIndex() != -1) {
			SocketConnectionBean bean = (SocketConnectionBean) connectionsList
					.getSelectedValue();
			if (bean != null) {
				TransmitClient client = bean.getClient();
				if (client != null) {
					client.close();

				}
			}
			DefaultListModel model = (DefaultListModel) connectionsList
					.getModel();
			model.remove(connectionsList.getSelectedIndex());
		}
	}

	private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_connectBtnActionPerformed
		final SocketConnectionBean bean = (SocketConnectionBean) connectionsList
				.getSelectedValue();
		if (bean != null) {
			final TransmitClient client = new TransmitClient(bean.getIp(), bean
					.getPort(), bean.getClientAddress(), bean
					.getSubServerType());

			new SwingWorker() {

				public Object construct() {
					connectBtn.setEnabled(false);
					boolean flag = true;
					try {
						client.connect();
						client.login();
					} catch (UnknownHostException e) {
						e.printStackTrace();
						bean.appendException(e);
						flag = false;
					} catch (IOException e) {
						e.printStackTrace();
						bean.appendException(e);
						flag = false;
					}
					return new Boolean(flag);
				}

				public void finished() {
					connectBtn.setEnabled(true);
					boolean flag = ((Boolean) get()).booleanValue();
					bean.setConnected(flag);
					if (flag == true) {
						bean.setClient(client);
						client
								.registerDataReceivedHandler(new DemoDataReceivedHandler(
										bean));
					}
				}

			}.start();

		}

	}

	private void disConnectBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_disConnectBtnActionPerformed
		SocketConnectionBean bean = (SocketConnectionBean) connectionsList
				.getSelectedValue();
		if (bean != null) {
			TransmitClient client = bean.getClient();
			if (client != null) {
				client.logout();
			}
			bean.setConnected(false);
		}
	}

	private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearBtnActionPerformed
		SocketConnectionBean bean = (SocketConnectionBean) connectionsList
				.getSelectedValue();
		if (bean != null) {
			bean.setFilePath("");
			bean.setInfoText("");
		}
	}

	private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendBtnActionPerformed
		String timesTxt = timesField.getText().trim();
		try {
			int times = Integer.parseInt(timesTxt);
			for (int i = 0; i < times; i++) {
				SocketConnectionBean bean = (SocketConnectionBean) connectionsList
						.getSelectedValue();
				// SendFile sendFile = null;
				// if (bean.getSubServerType() ==
				// ControlCode.DIRECTION_FROM_TREMINAL)
				// sendFile = new SendFile(bean.getFilePath(), bean
				// .getForwardAddress(), bean.getClientAddress(), bean
				// .getClient());
				// else
				// sendFile = new SendFile(bean.getFilePath(), bean
				// .getClientAddress(), bean.getForwardAddress(), bean
				// .getClient());
				// try {
				// sendFile.send();
				// } catch (IOException e) {
				// bean.appendException(e);
				// }
				final int command = 1234;
				RequestHandler reuqestHandler = new RequestHandler(bean
						.getClient(), command) {

					public void requestFinished(TransmitData[] data, int fseq) {
						System.out.println("Request callback, for " + fseq);
					}

					public void requestFailedTimeout() {
						System.err.println(command);

					}

				};
				TransmitSender sender = new TransmitFileSender(
						bean.getClient(), bean.getForwardAddress(), new File(
								bean.getFilePath()),false);
				sender.send(reuqestHandler.getUserCommand(), reuqestHandler);
			}
		} catch (Exception e) {
			JOptionPane.showConfirmDialog(this,
					"Times values must be mumberic!", "Warn",
					JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
			return;
		}

	}

	private void hexCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_hexCheckBoxActionPerformed
		SocketConnectionBean bean = (SocketConnectionBean) connectionsList
				.getSelectedValue();
		if (bean != null) {
			bean.setHex(hexCheckBox.isSelected());
		}
	}

	private void fileChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fileChooseBtnActionPerformed
		SocketConnectionBean bean = (SocketConnectionBean) connectionsList
				.getSelectedValue();
		String defaultCancel = (String) UIManager
				.get("FileChooser.cancelButtonText");
		UIManager.put("FileChooser.cancelButtonText", "Close Me");
		JFileChooser chooser = new JFileChooser();
		chooser.setMultiSelectionEnabled(false);
		int result = chooser.showDialog(this, "Choose Me");
		if (result == JFileChooser.APPROVE_OPTION) {
			if (bean != null)
				bean.setFilePath(chooser.getSelectedFile().getAbsolutePath());
		}
		UIManager.put("FileChooser.cancelButtonText", defaultCancel);
	}

	private void fileCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
		SocketConnectionBean bean = (SocketConnectionBean) connectionsList
				.getSelectedValue();
		if (bean != null) {
			bean.setFileTranmit(fileCheckBox.isSelected());
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton clearBtn;
	private javax.swing.JButton connectBtn;
	private javax.swing.JList connectionsList;
	private javax.swing.JButton delConnBtn;
	private javax.swing.JButton disConnectBtn;
	private javax.swing.JButton fileChooseBtn;
	private javax.swing.JCheckBox hexCheckBox;
	private javax.swing.JCheckBox fileCheckBox;
	private javax.swing.JTextArea infoArea;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextField pathField;
	private javax.swing.JTextField timesField;
	private javax.swing.JButton newConnBtn;
	private javax.swing.JButton sendBtn;
	private javax.swing.JTextArea simpleInputArea;
	private javax.swing.JSplitPane jSplitPane1;

	// End of variables declaration//GEN-END:variables

	public javax.swing.JButton getClearBtn() {
		return clearBtn;
	}

	public javax.swing.JButton getConnectBtn() {
		return connectBtn;
	}

	public javax.swing.JList getConnectionsList() {
		return connectionsList;
	}

	public javax.swing.JButton getDelConnBtn() {
		return delConnBtn;
	}

	public javax.swing.JButton getDisConnectBtn() {
		return disConnectBtn;
	}

	public javax.swing.JButton getFileChooseBtn() {
		return fileChooseBtn;
	}

	public javax.swing.JCheckBox getHexCheckBox() {
		return hexCheckBox;
	}

	public javax.swing.JTextArea getInfoArea() {
		return infoArea;
	}

	public javax.swing.JTextField getPathField() {
		return pathField;
	}

	public javax.swing.JButton getNewConnBtn() {
		return newConnBtn;
	}

	public javax.swing.JButton getSendBtn() {
		return sendBtn;
	}

	public javax.swing.JTextArea getSimpleInputArea() {
		return simpleInputArea;
	}

	public javax.swing.JCheckBox getFileCheckBox() {
		return fileCheckBox;
	}

	private class DemoDataReceivedHandler implements DataReceivedHandler {

		private SocketConnectionBean bean;

		private int serial = 0;

		private synchronized int getSerial() {
			serial++;
			return serial;
		}

		private DemoDataReceivedHandler(SocketConnectionBean bean) {
			// super(bean.getClient());
			this.bean = bean;
		}

		public void failedReceivedMultiple(TransmitData[] data) {
			bean.appendInfo("Multiple data receive Error!");
		}

		public void onReceived(TransmitData[] data) {
			// 接收到多帧时写文件
			String fileName = bean.getClientAddress() + "C"
					+ bean.getForwardAddress() + "F-" + getSerial() + ".tmp";
			String wholePath = System.getProperty("user.home") + "/" + fileName;
			File f = new File(wholePath);
			bean.appendInfo("Received data, will be written into \""
					+ f.getAbsolutePath() + "\"");
			if (f.exists()) {
				f.delete();
			}
			int command = TransmitClient.COMMAND_NO;
			int fseq = 0;
			try {
				f.createNewFile();

				FileOutputStream fos = new FileOutputStream(f);
				for (int i = 0; i < data.length; i++) {
					TransmitData oneFrame = data[i];
					if (oneFrame == null)
						continue;

					byte[] content = UnPackageMessage.getData(oneFrame
							.getOneFrameData());
					if (i == 0 && content.length > 1) {
						int height = (content[1] + 256) % 256;
						int low = (content[0] + 256) % 256;
						command = height * 256 + low;
						fseq = UnPackageMessage.getFSEQ(oneFrame
								.getOneFrameData());
						bean.appendInfo("received command:"
								+ String.valueOf(command));
						fos.write(content, TransmitClient.COMMAND_BYTES_LENGTH,
								content.length
										- TransmitClient.COMMAND_BYTES_LENGTH);
					} else
						fos.write(content);
				}
				fos.flush();
				fos.close();
			} catch (FileNotFoundException e) {
				e.printStackTrace();
				bean.appendException(e);
			} catch (IOException e) {
				e.printStackTrace();
				bean.appendException(e);
			}
			// demo ,终端收到后的反馈
			if (bean.getClient().getSubServerType() == ControlCode.DIRECTION_FROM_TREMINAL) {
				int toAddress;

				if (bean.getClient().getSubServerType() == ControlCode.DIRECTION_FROM_APPLICATION) {
					toAddress = UnPackageMessage.getConsumerAddress(data[0]
							.getOneFrameData());
				} else {
					toAddress = UnPackageMessage.getManufactureAddress(data[0]
							.getOneFrameData());
				}
				try {
					TransmitSender sender = new DemoTransmitFileSender(bean
							.getClient(), toAddress, new File("D:/xx.png"),true);
					sender.feedBack(fseq);
				} catch (UMSTransmitException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (OutOfMaxFrameSizeException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IllegalCommandException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
	}
}
