/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewConnPanel.java
 *
 * Created on 2009-8-28, 15:33:19
 */

package com.ums.demo.panels;

/**
 *
 * @author Qil.Wong
 */
public class NewConnPanel extends javax.swing.JPanel {

    /** Creates new form NewConnPanel */
    public NewConnPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clientAddressField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        subServerTypeCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        serverField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        forwardAddressField = new javax.swing.JTextField();

        jLabel1.setText("Client Address:");
        jLabel1.setName("jLabel1"); // NOI18N

        clientAddressField.setName("clientAddressField"); // NOI18N

        jLabel2.setText("Type:");
        jLabel2.setName("jLabel2"); // NOI18N

        subServerTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Application", "Terminal" }));
        subServerTypeCombo.setName("subServerTypeCombo"); // NOI18N

        jLabel3.setText("Remote Server:");
        jLabel3.setName("jLabel3"); // NOI18N

        serverField.setText("127.0.0.1:10234");
        serverField.setName("serverField"); // NOI18N

        jLabel4.setText("Forward Address:");
        jLabel4.setName("jLabel4"); // NOI18N

        forwardAddressField.setName("forwardAddressField"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel1)
                    .add(jLabel4)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, clientAddressField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, forwardAddressField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, serverField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .add(subServerTypeCombo, 0, 118, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(clientAddressField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(forwardAddressField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(subServerTypeCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(serverField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientAddressField;
    private javax.swing.JTextField forwardAddressField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField serverField;
    private javax.swing.JComboBox subServerTypeCombo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the addressField
     */
    public javax.swing.JTextField getAddressField() {
        return clientAddressField;
    }

    /**
     * @return the serverField
     */
    public javax.swing.JTextField getServerField() {
        return serverField;
    }

    /**
     * @return the subServerTypeCombo
     */
    public javax.swing.JComboBox getSubServerTypeCombo() {
        return subServerTypeCombo;
    }

}
