/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransmitSocketPanel.java
 *
 * Created on 2009-8-27, 21:49:51
 */

package com.ums.demo.panels;

/**
 *
 * @author Qil.Wong
 */
public class TransmitSocketPanel extends javax.swing.JPanel {

    /** Creates new form TransmitSocketPanel */
    public TransmitSocketPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        connectionsList = new javax.swing.JList();
        newConnBtn = new javax.swing.JButton();
        delConnBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        connectBtn = new javax.swing.JButton();
        disConnectBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        sendBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        fileCheckBox = new javax.swing.JCheckBox();
        pathField = new javax.swing.JTextField();
        fileChooseBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        simpleInputArea = new javax.swing.JTextArea();
        hexCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        timesField = new javax.swing.JTextField();

        jSplitPane1.setBorder(null);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        connectionsList.setName("connectionsList"); // NOI18N
        jScrollPane1.setViewportView(connectionsList);

        newConnBtn.setText("New");
        newConnBtn.setName("newConnBtn"); // NOI18N
        newConnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConnBtnActionPerformed(evt);
            }
        });

        delConnBtn.setText("Delete");
        delConnBtn.setName("delConnBtn"); // NOI18N
        delConnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delConnBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Connections:");
        jLabel2.setName("jLabel2"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(newConnBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(delConnBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {delConnBtn, newConnBtn}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(8, 8, 8)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(delConnBtn)
                    .add(newConnBtn))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel4.setName("jPanel4"); // NOI18N

        connectBtn.setText("Connect");
        connectBtn.setName("connectBtn"); // NOI18N
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });

        disConnectBtn.setText("Disconnect");
        disConnectBtn.setName("disConnectBtn"); // NOI18N
        disConnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disConnectBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.setName("clearBtn"); // NOI18N
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        sendBtn.setText("Send");
        sendBtn.setName("sendBtn"); // NOI18N
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        infoArea.setColumns(20);
        infoArea.setEditable(false);
        infoArea.setRows(5);
        infoArea.setName("infoArea"); // NOI18N
        jScrollPane2.setViewportView(infoArea);

        fileCheckBox.setText("File Input:");
        fileCheckBox.setEnabled(false);
        fileCheckBox.setName("fileCheckBox"); // NOI18N
        fileCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileCheckBoxActionPerformed(evt);
            }
        });

        pathField.setEditable(false);
        pathField.setName("pathField"); // NOI18N

        fileChooseBtn.setText("Choose");
        fileChooseBtn.setEnabled(false);
        fileChooseBtn.setName("fileChooseBtn"); // NOI18N
        fileChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Simple Input"));
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane3.setBorder(null);
        jScrollPane3.setName("jScrollPane3"); // NOI18N

        simpleInputArea.setColumns(20);
        simpleInputArea.setEditable(false);
        simpleInputArea.setRows(5);
        simpleInputArea.setName("simpleInputArea"); // NOI18N
        jScrollPane3.setViewportView(simpleInputArea);

        hexCheckBox.setText("Hex Format");
        hexCheckBox.setEnabled(false);
        hexCheckBox.setName("hexCheckBox"); // NOI18N
        hexCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexCheckBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
            .add(jPanel2Layout.createSequentialGroup()
                .add(hexCheckBox)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(hexCheckBox))
        );

        jLabel1.setText(" Times:");
        jLabel1.setName("jLabel1"); // NOI18N

        timesField.setText("1");
        timesField.setName("timesField"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(connectBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(disConnectBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(clearBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 172, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(timesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sendBtn))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(fileCheckBox)
                        .add(18, 18, 18)
                        .add(pathField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fileChooseBtn))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(new java.awt.Component[] {connectBtn, disConnectBtn}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel4Layout.linkSize(new java.awt.Component[] {clearBtn, fileChooseBtn, sendBtn}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fileCheckBox)
                    .add(pathField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fileChooseBtn))
                .add(14, 14, 14)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(disConnectBtn)
                        .add(sendBtn)
                        .add(clearBtn)
                        .add(timesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel1))
                    .add(connectBtn))
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_connectBtnActionPerformed

    private void newConnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConnBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newConnBtnActionPerformed

    private void delConnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delConnBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delConnBtnActionPerformed

    private void disConnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disConnectBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disConnectBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtnActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendBtnActionPerformed

    private void hexCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hexCheckBoxActionPerformed

    private void fileChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fileChooseBtnActionPerformed

    private void fileCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fileCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton connectBtn;
    private javax.swing.JList connectionsList;
    private javax.swing.JButton delConnBtn;
    private javax.swing.JButton disConnectBtn;
    private javax.swing.JCheckBox fileCheckBox;
    private javax.swing.JButton fileChooseBtn;
    private javax.swing.JCheckBox hexCheckBox;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton newConnBtn;
    private javax.swing.JTextField pathField;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextArea simpleInputArea;
    private javax.swing.JTextField timesField;
    // End of variables declaration//GEN-END:variables

}
