/*
 * AboutPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nci.svg.ui.about;

import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

import chrriis.dj.nativeswing.ui.JWebBrowser;

import com.nci.svg.ui.HyperLinkLabel;
import com.nci.svg.util.Utilities;

import fr.itris.glips.svgeditor.resources.ResourcesManager;

/**
 * 
 * @author Qil.Wong
 */
public class SVGAboutPanel extends javax.swing.JPanel {

	private Component parent;

	public SVGAboutPanel(Component parent) {
		initComponents();
		this.parent = parent;
		addHotKey();
	}

	public void addHotKey() {
		okBtn.setMnemonic(java.awt.event.KeyEvent.VK_O);
	}
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new HyperLinkLabel();
		jLabel5.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				Utilities.gotoWebSite("http://www.nci.com.cn","新世纪信息");
			}

		});
		okBtn = new javax.swing.JButton();
		Image logo = ResourcesManager.getIcon("Splash", false).getImage()
				.getScaledInstance(150, 160, Image.SCALE_SMOOTH);
		// BufferedImage bimage = new BufferedImage(logo);
		jLabel4 = new javax.swing.JLabel();

		jLabel1.setIcon(new ImageIcon(logo)); // NOI18N

		jLabel2.setText(ResourcesManager.bundle
				.getString("nci_VersionLabelText")); // NOI18N

		jLabel3.setText(ResourcesManager.bundle
				.getString("nci_svg_product_name")); // NOI18N

		jLabel5.setText(ResourcesManager.bundle.getString("nci_VisitWebSite")); // NOI18N

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel3,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				145,
																				Short.MAX_VALUE)
																		.add(
																				6,
																				6,
																				6))
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel2,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				139,
																				Short.MAX_VALUE)
																		.addContainerGap())
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel5)
																		.addContainerGap(
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel1Layout.createSequentialGroup().add(jLabel3)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jLabel2).addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jLabel5).addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		okBtn.setText(ResourcesManager.bundle.getString("OK")); // NOI18N
		okBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okBtnActionPerformed(evt);
			}
		});

		jLabel4.setText(ResourcesManager.bundle.getString("nci_copyright"));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.add(
																				jLabel1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				160,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.add(
																				jPanel1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jLabel4)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				81,
																				Short.MAX_VALUE)
																		.add(
																				okBtn,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				71,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(
																jLabel1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.add(
																jPanel1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel4)
														.add(okBtn))
										.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	// GEN-FIRST:event_jButton1ActionPerformed
	private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {
		parent.setVisible(false);
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private HyperLinkLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton okBtn;
	// End of variables declaration//GEN-END:variables

}