/*
 * SmsSettingPannel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nci.ums.desktop.panels;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import com.nci.ums.desktop.ConsoleUtil;

/**
 * 
 * @author __USER__
 */
public class SmsSettingPannel extends javax.swing.JPanel implements Setting {

	private static String propFile = "/resources/reserve.properties";

	/** Creates new form SmsSettingPannel */
	public SmsSettingPannel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		cmReserve_CNText = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		cmReserve_ENText = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		cuReserve_CNText = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		cuReserve_ENText = new javax.swing.JTextField();

		jLabel1.setText(ConsoleUtil.getLocaleString("Short_Message_signing_information"));

		jLabel2.setText(ConsoleUtil.getLocaleString("China_Mobile_Signing_Chinese:"));

		jLabel3.setText(ConsoleUtil.getLocaleString("China_Mobile_Signing_English:"));

		jLabel4.setText(ConsoleUtil.getLocaleString("China_Unicom_Signing_Chinese:"));

		jLabel5.setText(ConsoleUtil.getLocaleString("China_Unicom_Signing_English:"));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								jLabel3)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								jLabel2)))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				10,
																				10,
																				10)
																		.add(
																				jLabel5))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				10,
																				10,
																				10)
																		.add(
																				jLabel4)))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																cmReserve_ENText,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																116,
																Short.MAX_VALUE)
														.add(
																cmReserve_CNText,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																116,
																Short.MAX_VALUE)
														.add(
																cuReserve_CNText,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																116,
																Short.MAX_VALUE)
														.add(
																cuReserve_ENText,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																116,
																Short.MAX_VALUE))
										.addContainerGap()).add(
								layout.createSequentialGroup().add(10, 10, 10)
										.add(jLabel1).addContainerGap(124,
												Short.MAX_VALUE)));

		layout.linkSize(new java.awt.Component[] { jLabel2, jLabel3 },
				org.jdesktop.layout.GroupLayout.HORIZONTAL);

		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel1)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel2)
														.add(
																cmReserve_CNText,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel3)
														.add(
																cmReserve_ENText,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel4)
														.add(
																cuReserve_CNText,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel5)
														.add(
																cuReserve_ENText,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
	}// </editor-fold>                        

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField cmReserve_CNText;
	private javax.swing.JTextField cmReserve_ENText;
	private javax.swing.JTextField cuReserve_CNText;
	private javax.swing.JTextField cuReserve_ENText;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;

	// End of variables declaration                   

	public void implSetting() throws IOException {
		String[] parameterNames = new String[] { "SMSReserved_GBK_cm",
				"SMSReserved_ISO_cm", "SMSReserved_GBK_cu",
				"SMSReserved_ISO_cu" };
		String[] values = new String[] { ConsoleUtil.toUnicode(cmReserve_CNText.getText(),false),
				cmReserve_ENText.getText(), ConsoleUtil.toUnicode(cuReserve_CNText.getText(),false),
				cuReserve_ENText.getText() };
		String path = getClass().getResource(propFile).getPath();
		ConsoleUtil.replacePropFile(parameterNames, values, path);
	}

	public void initSetting() throws IOException {
		Properties props = new Properties();
		InputStream is = getClass().getResourceAsStream(propFile);
		props.load(is);
		cmReserve_CNText.setText(props.getProperty("SMSReserved_GBK_cm"));
		cmReserve_ENText.setText(props.getProperty("SMSReserved_ISO_cm"));
		cuReserve_CNText.setText(props.getProperty("SMSReserved_GBK_cu"));
		cuReserve_ENText.setText(props.getProperty("SMSReserved_ISO_cu"));
		is.close();
	}


}

