/*
 * VoltageClassDialog.java
 *
 * Created on July 14, 2008, 10:53 PM
 */

package com.nci.svg.ui.liifecycle;

import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import fr.itris.glips.svgeditor.Editor;

/**
 *
 * @author  Qil.Wong
 */
public class VoltageClassDialog extends javax.swing.JDialog {

    
    private String selectedVoltatge = null;
    
    private DefaultListModel listModel = new DefaultListModel();
    
    /** Creates new form VoltageClassDialog */
    public VoltageClassDialog(Editor editor, boolean modal) {
        super(editor.findParentFrame(), modal);
        initComponents();
        voltageList.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        voltageList.setModel(listModel);
        this.setLocationRelativeTo(editor.findParentFrame());
        okBtn.setEnabled(false);
        voltageList.getSelectionModel().addListSelectionListener(new ListSelectionListener(){

			public void valueChanged(ListSelectionEvent e) {
				// TODO Auto-generated method stub
				okBtn.setEnabled(true);
			}
        	
        });
    }
    
    public void setValue(ArrayList<String> voltageNames){
        for(int i=listModel.size()-1;i>=0;i--){
            listModel.remove(i);
        }
        for(String voltage:voltageNames){
            listModel.addElement(voltage);
        }
    }
    
    private void setSelectedVoltage(String voltage){
        selectedVoltatge = voltage;
    }
    
    public String getSelectedVoltage(){
        return selectedVoltatge;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        voltageList = new javax.swing.JList();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(voltageList);

        okBtn.setText("È·¶¨");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .add(okBtn))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(okBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
// TODO add your handling code here:
    setSelectedVoltage(voltageList.getSelectedValue().toString());
    this.setVisible(false);
}//GEN-LAST:event_okBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okBtn;
    private javax.swing.JList voltageList;
    // End of variables declaration//GEN-END:variables

}
