/*
 * EquipObjrefPanel.java
 *
 * Created on 2008年8月18日, 上午9:55
 */

package com.nci.svg.equip;

import javax.swing.JDialog;

import org.w3c.dom.Element;

/**
 *
 * @author  yx.nci
 */
public class EquipObjrefPanel extends javax.swing.JPanel {

    private Element element = null;
    private JDialog dialog = null;
    /** Creates new form EquipObjrefPanel */
    public EquipObjrefPanel(Element element,JDialog dialog) {
        this.element = element;
        this.dialog = dialog;
        initComponents();
    }
    private void saveData()
    {
        Element ObjectRef = (Element)((Element)element.getParentNode()).getElementsByTagName("PSR:ObjRef").item(0);
        if(ObjectRef != null)
        {
            ObjectRef.setAttribute("ObjectID", textObjectID.getText());
            ObjectRef.setAttribute("FieldNo", textFieldNo.getText());
            ObjectRef.setAttribute("Code", textCode.getText());
        }
    }
    
    private void initData()
    {
        Element ObjectRef = (Element)((Element)element.getParentNode()).getElementsByTagName("PSR:ObjRef").item(0);
        if(ObjectRef != null)
        {
            textObjectID.setText(ObjectRef.getAttribute("ObjectID"));
            textFieldNo.setText(ObjectRef.getAttribute("FieldNo"));
            textCode.setText(ObjectRef.getAttribute("Code"));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObjectID = new java.awt.Label();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        textObjectID = new java.awt.TextField();
        textFieldNo = new java.awt.TextField();
        textCode = new java.awt.TextField();
        buttonOK = new javax.swing.JButton();
        buttonCanel = new javax.swing.JButton();

        ObjectID.setText("ObjectID");

        label1.setText("FieldNo");

        label2.setText("Code");

        buttonOK.setText("确定");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonCanel.setText("取消");
        buttonCanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCanelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, textCode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, textFieldNo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, ObjectID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, textObjectID, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .add(buttonOK)
                .add(18, 18, 18)
                .add(buttonCanel)
                .add(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(ObjectID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textObjectID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textFieldNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonOK)
                    .add(buttonCanel))
                .add(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
// TODO add your handling code here:
    saveData();
    
    dialog.setVisible(false);
}//GEN-LAST:event_buttonOKActionPerformed

private void buttonCanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCanelActionPerformed
// TODO add your handling code here:
    dialog.setVisible(false);
}//GEN-LAST:event_buttonCanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label ObjectID;
    private javax.swing.JButton buttonCanel;
    private javax.swing.JButton buttonOK;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField textCode;
    private java.awt.TextField textFieldNo;
    private java.awt.TextField textObjectID;
    // End of variables declaration//GEN-END:variables

    public void setElement(Element element) {
        this.element = element;
        initData();
    }

}
