/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DoubleComboPanel.java
 *
 * Created on 2008-12-26, 16:35:05
 */

package com.nci.svg.sdk.ui;

/**
 *
 * @author yx.nci
 */
public class DoubleComboPanel extends javax.swing.JPanel {

    /** Creates new form DoubleComboPanel */
    public DoubleComboPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentText = new javax.swing.JLabel();
        sonText = new javax.swing.JLabel();
        parentCombo = new javax.swing.JComboBox();
        sonCombo = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(500, 80));

        parentText.setText("jLabel1");

        sonText.setText("jLabel2");

        parentCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sonCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sonText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(parentText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentText)
                    .addComponent(parentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sonText)
                    .addComponent(sonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox parentCombo;
    private javax.swing.JLabel parentText;
    private javax.swing.JComboBox sonCombo;
    private javax.swing.JLabel sonText;
    // End of variables declaration//GEN-END:variables
	/**
	 * 获取父下拉框对象�
	 * @return the parentCombo
	 */
	public javax.swing.JComboBox getParentCombo() {
		return parentCombo;
	}

	/**
	 * 获取显示文字对象
	 * @return the parentText
	 */
	public javax.swing.JLabel getParentText() {
		return parentText;
	}

	/**
	 * 获取子下拉框对象�
	 * @return the sonCombo
	 */
	public javax.swing.JComboBox getSonCombo() {
		return sonCombo;
	}

	/**
	 * 获取子显示文本对象
	 * @return the sonText
	 */
	public javax.swing.JLabel getSonText() {
		return sonText;
	}

}
