/*
 * AboutPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nci.ums.jmx.desktop.panels;

import java.awt.Component;

import com.nci.ums.jmx.ConsoleUtil;
import com.nci.ums.jmx.desktop.HotKey;

/**
 * 
 * @author Qil.Wong
 */
public class AboutPanel extends javax.swing.JPanel implements HotKey {

	private Component parent;

	/** Creates new form AboutPanel */
	public AboutPanel() {
		initComponents();
//		this.setBackground(new Color(new GradientPaint(0, 0, Color.GREEN, 200, 200, Color.blue,
//				false)));
	}

//	public void paint(Graphics g) {
//		Graphics2D g2 = (Graphics2D) g;
//		g2.setPaint(new GradientPaint(0, 0, Color.GREEN, 200, 200, Color.blue,
//				false));
//
//		Rectangle r = new Rectangle(0, 0, this.getWidth(), this.getHeight());
//
//		g2.fill(r);
//	}
	

	public AboutPanel(Component parent) {
		initComponents();
		// this.jLabel1.setIcon(new
		// ImageIcon("com/nci/ums/desktop/icons/about.jpg"));
		this.parent = parent;
		addHotKey();
	}

	public void addHotKey() {
		okBtn.setMnemonic(java.awt.event.KeyEvent.VK_O);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jideButton1 = new com.jidesoft.swing.JideButton();
        jLabel1 = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jideButton1.setText("jideButton1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nci/ums/jmx/desktop/icons/about.jpg"))); // NOI18N

        okBtn.setText(ConsoleUtil.getLocaleString("OK")); // NOI18N
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("(c) Copyright NCI.  All rights reserved.");

        jLabel3.setText(ConsoleUtil.getLocaleString("Uniform_Message_System")); // NOI18N

        jLabel2.setText(ConsoleUtil.getLocaleString("VersionLabelText")); // NOI18N

        jLabel5.setText("œÍ«È∑√Œ  http://www.nci.com.cn");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(77, 77, 77)
                                .add(okBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(14, 14, 14))
                            .add(layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                        .add(4, 4, 4))
                                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))))
                    .add(jLabel4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(okBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	// GEN-FIRST:event_jButton1ActionPerformed
	private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {
		parent.setVisible(false);
	}// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.jidesoft.swing.JideButton jideButton1;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables

}