/*
 * SettingDialog.java
 *
 * Created on 2007年11月5日, 下午8:22
 */
package com.ums.demo;

import com.nci.ums.v3.service.impl.UMS3_MsgSendStub;
import com.ums.demo.interfaces.Setting;
import com.ums.demo.panels.WSDLSettingPanel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.axis2.AxisFault;

/**
 *
 * @author  Qil.Wong
 */
public class SettingDialog extends javax.swing.JDialog {

    ArrayList<Setting> settingPanelList = new ArrayList<Setting>();
    UMSTestDemo parent;

    /** Creates new form SettingDialog */
    public SettingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        settingPanelList.add(this.wSDLSettingPanel1);
        settingPanelList.add(this.dBSettingPanel1);
        this.parent= (UMSTestDemo)parent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingTab = new javax.swing.JTabbedPane();
        dBSettingPanel1 = new com.ums.demo.panels.DBSettingPanel();
        wSDLSettingPanel1 = new com.ums.demo.panels.WSDLSettingPanel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");

        settingTab.addTab("DataBase", dBSettingPanel1);
        settingTab.addTab("wsdl", wSDLSettingPanel1);

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(okBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelBtn))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, settingTab, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {cancelBtn, okBtn}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(settingTab, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelBtn)
                    .add(okBtn))
                .addContainerGap())
        );

        settingTab.getAccessibleContext().setAccessibleName("wsdl");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        for (int i = 0; i < settingPanelList.size(); i++) {
            settingPanelList.get(i).implSetting();
            if(settingPanelList.get(i) instanceof WSDLSettingPanel){
                try {
                    String wsdl = ((WSDLSettingPanel) settingPanelList.get(i)).getWsdlField().getText();
                    parent.setStub(new UMS3_MsgSendStub(wsdl));
                } catch (AxisFault ex) {
                    Logger.getLogger(SettingDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        this.dispose();
}//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SettingDialog dialog = new SettingDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private com.ums.demo.panels.DBSettingPanel dBSettingPanel1;
    private javax.swing.JButton okBtn;
    private javax.swing.JTabbedPane settingTab;
    private com.ums.demo.panels.WSDLSettingPanel wSDLSettingPanel1;
    // End of variables declaration//GEN-END:variables
}
