/*
 * EuiPanel.java
 *
 * Created on __DATE__, __TIME__
 */
package com.nci.ums.jmx.desktop.panels;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import com.nci.ums.jmx.ConsoleUtil;

/**
 *
 * @author  __USER__
 */
public class EuiSettingPanel extends javax.swing.JPanel implements Setting {

    private String propFile = "/resources/eui.props";

    /** Creates new form EuiPanel */
    public EuiSettingPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        classNameText = new javax.swing.JTextField();

        jLabel2.setText(ConsoleUtil.getLocaleString("EnterpriseUserClass")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(classNameText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(classNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField classNameText;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    public void implSetting() throws IOException {
        String[] parameterNames = new String[]{"euiClass"};
        String[] parameterValues = new String[]{classNameText.getText().trim()};
        String path = getClass().getResource(propFile).getPath();
        ConsoleUtil.replacePropFile(parameterNames, parameterValues, path);
    }

    public void initSetting() throws IOException {
        Properties props = new Properties();
        InputStream is = getClass().getResourceAsStream(propFile);
        props.load(is);
        String className = props.getProperty("euiClass");
        classNameText.setText(className);
        is.close();
    }
}
