/*
 * OtherSettingPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nci.ums.jmx.desktop.panels;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import com.nci.ums.jmx.ConsoleUtil;
import com.nci.ums.jmx.desktop.bean.NumOnlyDocument;

/**
 *
 * @author  __USER__
 */
public class MsgReceiveSettingPanel extends javax.swing.JPanel implements
		Setting {

	private static String propFile = "/resources/receive.props";

	/** Creates new form OtherSettingPanel */
	public MsgReceiveSettingPanel() {
		initComponents();
		msgReceivePortText.setDocument(new NumOnlyDocument(5));
		timeOutText.setDocument(new NumOnlyDocument());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        msgReceivePortText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        timeOutText = new javax.swing.JTextField();

        jLabel1.setText(ConsoleUtil.getLocaleString("Message_receiving_Info")); // NOI18N

        jLabel2.setText(ConsoleUtil.getLocaleString("MsgReceivePort:")); // NOI18N

        jLabel3.setText(ConsoleUtil.getLocaleString("ReceiveTimeOut")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(timeOutText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .add(msgReceivePortText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .add(133, 133, 133))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(msgReceivePortText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(timeOutText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField msgReceivePortText;
    private javax.swing.JTextField timeOutText;
    // End of variables declaration//GEN-END:variables

	public void implSetting() throws IOException {
		String[] parameters = new String[]{"socket_port","time_out"};
		String[] values = new String[]{msgReceivePortText.getText(),timeOutText.getText()};
		String path = getClass().getResource(propFile).getPath();
		ConsoleUtil.replacePropFile(parameters, values, path);
	}

	public void initSetting() throws IOException {
		Properties props = new Properties();
		InputStream is = getClass().getResourceAsStream(propFile);
		props.load(is);
		msgReceivePortText.setText(props.getProperty("socket_port"));
		timeOutText.setText(props.getProperty("time_out"));
		is.close();
	}

}