CREATE TABLE UMS_SEND_OK  (
   BATCHNO              VARCHAR2(14)                    NOT null,
   SERIALNO             NUMBER(8)                       NOT null,
   SEQUENCENO           NUMBER                          NOT null,
   BATCHMODE            VARCHAR2(1),
   APPSERIALNO          VARCHAR2(35),
   RETCODE              VARCHAR2(10),
   ERRMSG               VARCHAR2(60),
   STATUSFLAG           NUMBER,
   SERVICEID            VARCHAR2(20),
   SENDDIRECTLY         NUMBER,
   MEDIAID              VARCHAR2(3),
   SENDID               VARCHAR2(60),
   SENDERTYPE           NUMBER(1),
   RECVID               VARCHAR2(60),
   RECEIVERTYPE         NUMBER(1),
   SUBMITDATE           VARCHAR2(8),
   SUBMITTIME           VARCHAR2(6),
   FINISHDATE           VARCHAR2(8),
   FINISHTIME           VARCHAR2(6),
   REP                  NUMBER,
   DOCOUNT              NUMBER,
   PRIORITY             NUMBER(1),
   CONTENTSUBJECT       VARCHAR2(50),
   CONTENT              VARCHAR2(1000),
   MSGID                VARCHAR2(20),
   TIMESETFLAG          NUMBER(1),
   SETDATE              VARCHAR2(8),
   SETTIME              VARCHAR2(6),
   INVALIDDATE          VARCHAR2(8),
   INVALIDTIME          VARCHAR2(6),
   ACK                  NUMBER(1),
   REPLYDESTINATION     VARCHAR2(60),
   NEEDREPLY            NUMBER(1),
   FEESERVICENO         VARCHAR2(20),
   FEE                  NUMBER,
   FEETYPE              NUMBER(1),
   UMSFLAG              NUMBER,
   COMPANYID            VARCHAR2(20),
   SEQKEY               VARCHAR2(36)                    NOT null,
   SENDERIDTYPE         VARCHAR2(32),
   RECEIVERIDTYPE       VARCHAR2(32),
   CONTENTMODE          NUMBER,
   CONSTRAINT PK_UMS_SEND_OK PRIMARY KEY (SEQKEY)
           USING index
);

COMMENT ON TABLE UMS_SEND_OK is '外拨已发送表';

COMMENT ON COLUMN UMS_SEND_OK.BATCHNO is '批号（8位日期+6位序号）';

COMMENT ON COLUMN UMS_SEND_OK.SERIALNO is '交易流水号';

COMMENT ON COLUMN UMS_SEND_OK.SEQUENCENO is '消息序号';

COMMENT ON COLUMN UMS_SEND_OK.BATCHMODE is '批量属性（0：单笔，1批量）';

COMMENT ON COLUMN UMS_SEND_OK.APPSERIALNO is '应用生成消息序号';

COMMENT ON COLUMN UMS_SEND_OK.RETCODE is '交易结果';

COMMENT ON COLUMN UMS_SEND_OK.ERRMSG is '错误信息';

COMMENT ON COLUMN UMS_SEND_OK.STATUSFLAG is '状态（0：正常，1：未就绪）';

COMMENT ON COLUMN UMS_SEND_OK.SERVICEID is '服务号';

COMMENT ON COLUMN UMS_SEND_OK.SENDDIRECTLY is '是否直接从指定渠道发送';

COMMENT ON COLUMN UMS_SEND_OK.MEDIAID is '渠道标识';

COMMENT ON COLUMN UMS_SEND_OK.SENDID is '发送方地址';

COMMENT ON COLUMN UMS_SEND_OK.SENDERTYPE is '发送者角色(FROM：1）';

COMMENT ON COLUMN UMS_SEND_OK.RECVID is '接收方地址';

COMMENT ON COLUMN UMS_SEND_OK.RECEIVERTYPE IS '接收者角色(TO：2，CC：3)';

COMMENT ON COLUMN UMS_SEND_OK.SUBMITDATE IS '提交日期';

COMMENT ON COLUMN UMS_SEND_OK.SUBMITTIME IS '提交时间';

COMMENT ON COLUMN UMS_SEND_OK.FINISHDATE IS '完成日期';

COMMENT ON COLUMN UMS_SEND_OK.FINISHTIME IS '完成时间';

COMMENT ON COLUMN UMS_SEND_OK.REP IS '当前渠道重复发生次数';

COMMENT ON COLUMN UMS_SEND_OK.DOCOUNT IS '累计次数';

COMMENT ON COLUMN UMS_SEND_OK.PRIORITY IS '优先级别';

COMMENT ON COLUMN UMS_SEND_OK.CONTENTSUBJECT IS '标题';

COMMENT ON COLUMN UMS_SEND_OK.CONTENT IS '信息内容';

COMMENT ON COLUMN UMS_SEND_OK.MSGID IS '消息编号';

COMMENT ON COLUMN UMS_SEND_OK.TIMESETFLAG IS '定时发送标志(0:非定时,1:定时)';

COMMENT ON COLUMN UMS_SEND_OK.SETDATE IS '定时发送日期';

COMMENT ON COLUMN UMS_SEND_OK.SETTIME IS '定时发送时间';

COMMENT ON COLUMN UMS_SEND_OK.INVALIDDATE IS '失效日期';

COMMENT ON COLUMN UMS_SEND_OK.INVALIDTIME IS '失效时间';

COMMENT ON COLUMN UMS_SEND_OK.ACK IS '回执标志';

COMMENT ON COLUMN UMS_SEND_OK.REPLYDESTINATION IS '回复目的地编号';

COMMENT ON COLUMN UMS_SEND_OK.NEEDREPLY IS '消息回复标志';

COMMENT ON COLUMN UMS_SEND_OK.FEESERVICENO IS '计费服务号';

COMMENT ON COLUMN UMS_SEND_OK.FEE IS '费用';

COMMENT ON COLUMN UMS_SEND_OK.FEETYPE IS '计费方式';

COMMENT ON COLUMN UMS_SEND_OK.UMSFLAG IS '消息所要发向UMS标志(1:自身,2:其他UMS)';

COMMENT ON COLUMN UMS_SEND_OK.COMPANYID IS '如果UMSFLAG为2,则表示消息将发往哪个company';

COMMENT ON COLUMN UMS_SEND_OK.SEQKEY IS '内码';

COMMENT ON COLUMN UMS_SEND_OK.SENDERIDTYPE IS '发送者类型';

COMMENT ON COLUMN UMS_SEND_OK.RECEIVERIDTYPE IS '接受者类型';

COMMENT ON COLUMN UMS_SEND_OK.CONTENTMODE IS '内容编码';