/*
 * GraphUnitSimpleSearchPanel.java
 *
 * Created on 2008-12-2, 15:49:14
 */
package com.nci.svg.sdk.ui.graphunit.search;

import java.util.Collections;
import java.util.Iterator;
import java.util.Map;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JTextField;

import com.nci.svg.sdk.client.EditorAdapter;
import com.nci.svg.sdk.client.util.StringPinyinComparator;
import com.nci.svg.sdk.graphunit.NCIEquipSymbolBean;
import com.nci.svg.sdk.graphunit.SymbolTypeBean;
import com.nci.svg.sdk.ui.EditorPanel;
import com.nci.svg.sdk.ui.autocomplete.AutoCompletionField;
import com.nci.svg.sdk.ui.autocomplete.DefaultCompletionFilter;

import fr.itris.glips.svgeditor.resources.ResourcesManager;

/**
 * 图元或模板查询小窗口
 * @author Qil.Wong
 */
public class GraphUnitSimpleSearchPanel extends EditorPanel {

	private static final long serialVersionUID = 4053614697750927224L;

	
	public GraphUnitSimpleSearchPanel(EditorAdapter editor) {
        super(editor);
        initComponents();
        
        closeBtn.setIcon(ResourcesManager.getIcon("FileClose", false));
        refreshAutoCompleteFilter();
    }
    
    /**
     * 设置自动取值的过滤器
     */
    public void refreshAutoCompleteFilter(){
    	Vector v = new Vector();      
        Map<SymbolTypeBean, Map<String, NCIEquipSymbolBean>> map = editor.getSymbolManager().getAllSymbols();
        Iterator<Map<String, NCIEquipSymbolBean>> it = map.values().iterator();
        Map<String, NCIEquipSymbolBean> temp = null;
        NCIEquipSymbolBean tempBean = null;
        while (it.hasNext()) {
        	temp = it.next();
        	if(temp!=null){
        		Iterator<NCIEquipSymbolBean> it2 = temp.values().iterator();
        		while(it2.hasNext()){
        			tempBean = it2.next();
        			v.add(tempBean.getName());
        		}
        	}
        }
        //排序，按字母，拼音字母排序
        Collections.sort(v, new StringPinyinComparator());
        ((AutoCompletionField) searchContentTxt).setFilter(new DefaultCompletionFilter(v));
    }



    public JTextField getTextField(){
        return searchContentTxt;
    }

    public JButton getCloseButton(){
        return closeBtn;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchContentTxt = new AutoCompletionField();
        closeBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(224, 26));

        jLabel1.setText("搜索:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(searchContentTxt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .add(3, 3, 3)
                .add(closeBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(closeBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(searchContentTxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField searchContentTxt;
    // End of variables declaration//GEN-END:variables
}
